<Project>
	<PropertyGroup>
		<MainScreenIndex>3</MainScreenIndex>
	</PropertyGroup>
	<ScreenMakerVersion>6.8</ScreenMakerVersion>
	<Type>FlexPendant</Type>
	<References />
	<Controller GUID="db981894-c35e-4a0d-a8a6-76f9cce300ac" Name="YOUNGSPAWNDELL" System="120-100761" />
	<AssemblyInfo>
		<Title></Title>
		<Description>Code generated by ScreenMaker - Internal version 6.8.8307.1040</Description>
		<Company></Company>
		<Product></Product>
		<Copyright></Copyright>
		<Trademark></Trademark>
		<Version>6.8.1040</Version>
	</AssemblyInfo>
	<TpsViewInfo>
		<Caption>FCT_Screen App</Caption>
		<MenuImageName>tpu-Operator32.png</MenuImageName>
		<TaskbarImageName>tpu-Operator32.png</TaskbarImageName>
		<StartPanelLocation>1</StartPanelLocation>
		<ViewType>1</ViewType>
		<StartupType>0</StartupType>
	</TpsViewInfo>
	<ApplicationVariables>
		<Variable Name="VarAntal" Value="0" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="VarZ" Value="0" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="VarX" Value="0" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="VarY" Value="0" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="VarFirekantType" Value="2" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="VarCirkelType" Value="1" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="VarTrekantType" Value="3" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
	</ApplicationVariables>
	<ItemGroup />
	<ItemGroup>
		<Compile Include=".\FCT_Screen_Firekant.view">
			<Link>FCT_Screen_Firekant.view</Link>
		</Compile>
		<Compile Include=".\FCT_Screen_Cirkel.view">
			<Link>FCT_Screen_Cirkel.view</Link>
		</Compile>
		<Compile Include=".\FCT_Screen_Trekant.view">
			<Link>FCT_Screen_Trekant.view</Link>
		</Compile>
		<Compile Include=".\FCT_MainScreen.view">
			<Link>FCT_MainScreen.view</Link>
		</Compile>
	</ItemGroup>
	<StartVirtualFlexPendant>False</StartVirtualFlexPendant>
	<FPSDKInfo>
		<Version>6.8.1040</Version>
	</FPSDKInfo>
	<WidgetInfo />
</Project>